# config_hermes.yaml
#
# List of news sources for Hermes to monitor.
# It can handle both RSS feeds and standard HTML websites.

sources:
  - name: "Reuters Technology"
    url: "http://feeds.reuters.com/reuters/technologyNews"
  - name: "Wired"
    url: "https://www.wired.com/feed/rss"
  - name: "MIT Technology Review"
    url: "https://www.technologyreview.com/feed/"
  - name: "Ars Technica"
    url: "http://feeds.arstechnica.com/arstechnica/index/"
  - name: "Hacker News" # Example of a non-RSS site it will crawl
    url: "https://news.ycombinator.com"

